# Generated by Django 3.1.3 on 2020-11-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201123_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImagesLic',
        ),
    ]
